engines:
  duplication:
    enabled: true
    config:
      languages:
        - php
        - javascript
  csslint:
    enabled: true
  eslint:
    enabled: true
    env:
      jquery: true
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"

ratings:
  paths:
    - "**.js"
    - "**.php"
    - "**.css"

exclude_paths:
  - test/